### ISSUE TITLE
Merged chromosomes by telomere sequence?

### ISSUE THREAD

**Issue by dirkjanvw** [bcgsc/ntJoin#106]
Hi thanks for the the amazing tool! We would like to use it in a pipeline to scaffold many HiFi assemblies with ideally the same `k` and `w` values for all assemblies. Most of our chromosomes are just a couple contigs, so it shouldn't be a big issue I assumed. However, it turns out that `ntJoin` in many cases merges chromosomes based on telomere sequences. We even increased `w` value to 16,000 (higher than you tried for human assemblies) with `k` to 52. See this image for mummerplot (reference on x-axis, scaffolded assembly on y-axis):
<img width="923" alt="image" src="https://github.com/bcgsc/ntJoin/assets/72025902/f615b030-255b-4654-9c0d-0f52794a5540">

Do you think increasing the `w` size even more might solve this issue? I fear increasing `w` size even more might put too many HiFi contigs in the unscaffolded. Or is there a way of "masking" the telomere sequence to prevent this from happening? Or any other settings we might use?

**Comment by lcoombe** [comment]
Hi @dirkjanvw,

Thanks for reaching out! Could you also just let me know what command you ran? Just so I know the other parameters that you used.

Thank you for your interest in ntJoin!
Lauren

**Comment by dirkjanvw** [comment]
Yes sure! This is the way I ran it for the image you see above:
```
ntJoin assemble target=accessionA references=reference.fa target_weight='1' reference_weights='2' G=10000 agp=True no_cut=True overlap=False k=52 w=16000 mkt=True prefix=scaffolded_accessionA t=5
```

**Comment by lcoombe** [comment]
Thanks! And what are you using as your reference here - is it a reference genome build?

**Comment by dirkjanvw** [comment]
Yes it is GCF_002870075.4 (chromosome level from RefSeq), unmodified.

**Comment by lcoombe** [comment]
Ok great! So when using a reference genome (vs. a draft assembly) as the provided reference, I suggest setting `n=2` - Essentially what that will achieve is only retaining edges or connections in the graph that are also in the reference. Sometimes, I had seen situations like you are seeing where with the default `n=1` with a reference, you could get some of these telomere-driven unwanted joins.

Hopefully with that setting, you should not see those spurious joins - let me know if that fixes things!

**Comment by dirkjanvw** [comment]
Wow that was very simple! It solved the issue for us

**Comment by lcoombe** [comment]
Awesome! So glad that solved it!
