### ISSUE TITLE
Assertion error leading to deletion of scaffolds output file

### ISSUE THREAD

**Issue by psal591** [bcgsc/ntJoin#109]
Hello,

I am trying to run ntJoin on two different assemblies of the same sample which were done in a different way. One assembly has less contigs but is less complete, the other is more fragmented but is more complete. I am running ntJoin on a cluster using Slurm, with the following commands:

> module purge
> module load Apptainer
> 
> export APPTAINER_CMD="apptainer exec ntJoin-1.1.4.sif "
> 
> ${APPTAINER_CMD} ntJoin assemble target=FlyePolishedRedundansPurgeDups.BlobT.noProk.fasta target_weight=1 references='MasurcaPolcaRedundansPurgeDups.BlobT.noProk.fasta' reference_weights='2' prefix=ntjoin.out k=32 w=1000

However, I am getting an output with an "AssertionError", and I don't know what it means. Could it be because the two assemblies are very similar, or some other issue unrelated to that? Any help is appreciated. I pasted the log file below.
Thank you!

> indexlr --seq --long --pos -k 32 -w 500 -t 4 MasurcaPolcaRedundansPurgeDups.BlobT.noProk.fasta > MasurcaPolcaRedundansPurgeDups.BlobT.noProk.fasta.k32.w500.tsv
> indexlr --seq --long --pos -k 32 -w 500 -t 4 FlyePolishedRedundansPurgeDups.BlobT.noProk.fasta > FlyePolishedRedundansPurgeDups.BlobT.noProk.fasta.k32.w500.tsv
> samtools faidx MasurcaPolcaRedundansPurgeDups.BlobT.noProk.fasta
> samtools: /opt/miniconda/bin/../lib/libtinfow.so.6: no version information available (required by samtools)
> samtools: /opt/miniconda/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
> samtools: /opt/miniconda/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
> samtools faidx FlyePolishedRedundansPurgeDups.BlobT.noProk.fasta
> samtools: /opt/miniconda/bin/../lib/libtinfow.so.6: no version information available (required by samtools)
> samtools: /opt/miniconda/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
> samtools: /opt/miniconda/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
> /opt/miniconda/bin/share/ntjoin-1.1.4-0/bin/ntjoin_run.py -p ntjoin.out -n 1 -s FlyePolishedRedundansPurgeDups.BlobT.noProk.fasta.k32.w500.tsv -l 1 \
> -r "2" -k 32 -g 20 -G 0 -t 1 --overlap --overlap_gap 20 --btllib_t 4 --overlap_k 15 --overlap_w 10 MasurcaPolcaRedundansPurgeDups.BlobT.noProk.fasta.k32.w500.tsv
> Running ntJoin scaffolding..
> Parameters:
>         Reference TSV files:  ['MasurcaPolcaRedundansPurgeDups.BlobT.noProk.fasta.k32.w500.tsv']
>         -s  FlyePolishedRedundansPurgeDups.BlobT.noProk.fasta.k32.w500.tsv
>         -l  1.0
>         -r  2
>         -p  ntjoin.out
>         -n  1
>         -k  32
>         -g  20
>         -G  0
>        -t  1
> Orienting contigs using increasing/decreasing minimizer positions
> 
>         --overlap
>         --overlap_gap 20
>         --overlap_k 15
>         --overlap_w 10
>         --btllib_t 4
> 2024-05-21 03:48:16.458446 : Reading minimizers MasurcaPolcaRedundansPurgeDups.BlobT.noProk.fasta.k32.w500.tsv
> 2024-05-21 03:48:23.177749 : Reading minimizers FlyePolishedRedundansPurgeDups.BlobT.noProk.fasta.k32.w500.tsv
> 2024-05-21 03:48:31.384897 : Generating minimizer graph ...
> 
> 
> Weights of assemblies:
> MasurcaPolcaRedundansPurgeDups.BlobT.noProk.fasta.k32.w500.tsv: 2.0
> FlyePolishedRedundansPurgeDups.BlobT.noProk.fasta.k32.w500.tsv: 1.0
> 
> 2024-05-21 03:48:31.385013 : Filtering minimizers
> 2024-05-21 03:48:35.328612 : Building graph
> 2024-05-21 03:48:49.652308 : Adding vertices
> 2024-05-21 03:48:49.989832 : Adding edges
> 2024-05-21 03:48:52.132871 : Adding attributes
> 2024-05-21 03:49:02.232126 : Printing graph ntjoin.out.mx.dot
> 
> file_name       number  colour
> MasurcaPolcaRedundansPurgeDups.BlobT.noProk.fasta.k32.w500.tsv  0       red
> FlyePolishedRedundansPurgeDups.BlobT.noProk.fasta.k32.w500.tsv  1       green
> 
> 2024-05-21 03:49:18.070649 : Filtering the graph
> 2024-05-21 03:49:27.772126 : Reading fasta file FlyePolishedRedundansPurgeDups.BlobT.noProk.fasta
> 2024-05-21 03:49:29.213093 : Finding paths
> 
> Total number of components in graph: 20 
> 
> 2024-05-21 03:50:04.567572 : Printing output scaffolds
> Traceback (most recent call last):
>   File "/opt/miniconda/bin/share/ntjoin-1.1.4-0/bin/ntjoin_run.py", line 69, in <module>
>     main()
>   File "/opt/miniconda/bin/share/ntjoin-1.1.4-0/bin/ntjoin_run.py", line 65, in main
>     NtjoinScaffolder(args).main_scaffolder()
>   File "/opt/miniconda/bin/share/ntjoin-1.1.4-0/bin/ntjoin_assemble.py", line 785, in main_scaffolder
>     self.print_scaffolds(paths, intersecting_regions, incorporated_segments)
>   File "/opt/miniconda/bin/share/ntjoin-1.1.4-0/bin/ntjoin_assemble.py", line 573, in print_scaffolds
>     assert len(my_seq) == node.get_aligned_length()
> AssertionError
> make: *** [/opt/miniconda/bin/share/ntjoin-1.1.4-0/ntJoin:229: FlyePolishedRedundansPurgeDups.BlobT.noProk.fasta.k32.w500.n1.assigned.sca
> ffolds.fa] Error 1
> make: *** Deleting file 'FlyePolishedRedundansPurgeDups.BlobT.noProk.fasta.k32.w500.n1.assigned.scaffolds.fa'

**Comment by lcoombe** [comment]
Hi @psal591,

Thanks for the report! That isn't an error that I have come across before, so bear with me while we go through some troubleshooting.

Just checking - have you run the test demo successfully with your ntJoin installation?

If that is successful, could you let me know the general stats of your assemblies, for example with `abyss-fac`? If you don't have abyss installed, I am most interested in the N50, number of sequences, whether your sequences have "N"s, and rough length distribution of the assemblies, including the minimum size of the contigs.
```
abyss-fac -t0 <assembly1> <assembly2>
```

Thank you for your interest in ntJoin!
Lauren

**Comment by psal591** [comment]
Hi Lauren,

Thank you for such a fast response! I confirm I have run the test demo
successfully with my ntJoin installation.
I know my assemblies are very fragmented (one much more than the other).
Here are the results from abyss-fac in my two assemblies:

> n       n:0     L50     min     N75     N50     N25     E-size  max
sum     name
>   7907    7907    595     1023    188925  452409  861980  609866  3935680
978.3e6 FlyePolishedRedundansPurgeDups.BlobT.noProk.fasta
>   3996    3996    669     1791    204362  389969  716351  529064  3121248
927.3e6 MasurcaPolcaRedundansPurgeDups.BlobT.noProk.fasta

In addition,for N's and length distribution, QUAST shows the following

> FlyePolishedRedundansPurgeDups.BlobT.noProk
> # contigs (>= 0 bp)         7907
>   # contigs (>= 1000 bp)      7907
>   # contigs (>= 5000 bp)      6865
>   # contigs (>= 10000 bp)     5700
>   # contigs (>= 25000 bp)     4107
>   # contigs (>= 50000 bp)     3046

> Total length (>= 0 bp)      978290921
>   Total length (>= 1000 bp)   978290921
>   Total length (>= 5000 bp)   974712479
>   Total length (>= 10000 bp)  966350157
>   Total length (>= 25000 bp)  940080887
>   Total length (>= 50000 bp)  902222847

> N's per 100 kbp           0.08
> Total length of the assembly               978290921

> MasurcaPolcaRedundansPurgeDups.BlobT.noProk
> contigs (>= 0 bp)         3996
>   # contigs (>= 1000 bp)      3996
>   # contigs (>= 5000 bp)      3970
>   # contigs (>= 10000 bp)     3932
>   # contigs (>= 25000 bp)     3716
>   # contigs (>= 50000 bp)     3343

>   Total length (>= 0 bp)      927759772
>   Total length (>= 1000 bp)   927759772
>   Total length (>= 5000 bp)   927670710
>   Total length (>= 10000 bp)  927381889
>   Total length (>= 25000 bp)  923425681
>   Total length (>= 50000 bp)  909360325

> N's per 100 kbp           52.17
> Total length of the assembly                927759772


If relevant, here are the BUSCOs of my assemblies
> FlyePolishedRedundansPurgeDups.BlobT.noProk.fasta
> C:93.2%[S:92.2%,D:1.0%],F:3.0%,M:3.8%,n:954
>   MasurcaPolcaRedundansPurgeDups.BlobT.noProk.fasta
> C:90.3%[S:89.0%,D:1.3%],F:3.7%,M:6.0%,n:954

Thank you again,

Priscila.

**Comment by lcoombe** [comment]
Thanks for that info, Priscila! That helps to narrow things down.

Ok, so I don't see any issues with your installation or the input assemblies. I'm wondering if there could be some sort of edge  case in your run that is triggering that assertion error.
Would you be open to re-running your job with a GitHub repository branch where I add a couple more informative messages to help me narrow down the issue? If you are OK with it, you can run the code in the same conda environment, but just add the path to the source code to the front of your path.

Let me know!
Lauren

**Comment by psal591** [comment]
Hi Laure,

I would be happy to! I might just need a bit more guidance on how to do
that. If I share my script with you, would you be happy to help me find
where to add the path to the source code?

Thank you,

Priscila.

**Comment by lcoombe** [comment]
Hi Priscila,

Thank you! And absolutely - I can definitely give you specific guidance.

First, if you clone the GitHub repository (`git clone https://github.com/bcgsc/ntJoin.git`), and checkout my branch (`git checkout troubleshoot_overlaps`), you'll have the correct source code.

Then, in your script, after activating your conda environment, prepend the path to the GitHub repository to your PATH (`export PATH=/path/to/git/clone/ntJoin/:$PATH`). You could add `which ntJoin` after that in your script to be sure that you are pointing to the expected installation.

I'm happy to point out where to put that in your script if you want to share it!

Thanks for your help,
Lauren

**Comment by psal591** [comment]
Hi Lauren,

I really appreciate your help, thank you.
I have cloned GitHib and checked out your branch, and then made a link to
each of my assemblies within that directory.

> ***@***.*** ntJoin_debug]$ git clone
https://github.com/bcgsc/ntJoin.git
>   Cloning into 'ntJoin'...
>   remote: Enumerating objects: 3451, done.
>   remote: Counting objects: 100% (816/816), done.
>   remote: Compressing objects: 100% (416/416), done.
>   remote: Total 3451 (delta 453), reused 679 (delta 376), pack-reused 2635
>   Receiving objects: 100% (3451/3451), 7.89 MiB | 13.81 MiB/s, done.
>   Resolving deltas: 100% (1745/1745), done.
> (base) ***@***.*** ntJoin_debug]$ cd ntJoin/
>   (base) ***@***.*** ntJoin]$ git checkout troubleshoot_overlaps
>   Branch 'troubleshoot_overlaps' set up to track remote branch
'troubleshoot_overlaps' from 'origin'.
>   Switched to a new branch 'troubleshoot_overlaps'
> (base) ***@***.*** ntJoin]$ ls
>   azure-pipelines.yml                                LICENSE
                               ntJoin           README.md         tests
>   bin                                                logo.png
                              ntjoin-logo.png  requirements.txt
>   FlyePolishedRedundansPurgeDups.BlobT.noProk.fasta
 MasurcaPolcaRedundansPurgeDups.BlobT.noProk.fasta  ntjoin.sh
 setup.py



When I first installed ntJoin, it was using a container image from github,
with the help of my cluster support . The command to run it uses Apptainer.
Should I append the path to export APPTAINER_CMD='apptainer exec
ntJoin-1.1.4.sif "

> (base) ***@***.*** ntJoin]$ less ntjoin.sh
> #!/bin/bash -e
>   #SBATCH --job-name=nJoint
>   #SBATCH --cpus-per-task=1
>   #SBATCH --mem=30G
>   #SBATCH --output=ntJoin/%j.out
>   #SBATCH --time=00:15:00
>   #SBATCH --ntasks=1

>   module purge
>   module load Apptainer

>   export APPTAINER_CMD="apptainer exec ntJoin-1.1.4.sif "

>   ${APPTAINER_CMD} ntJoin assemble
target=FlyePolishedRedundansPurgeDups.BlobT.noProk.fasta target_weight=1
references='MasurcaPolcaRedundansPurgeDups.BlobT.noProk.fasta'
reference_weights='1' prefix=ntjoin.out k=32 w=1000

**Comment by psal591** [comment]
Hi Lauren,

This is very generous of you. What is the best way for me to share the
assemblies with you?

Thank you heaps!

Priscila.

**Comment by lcoombe** [comment]
Hi Priscila,

You are very welcome! You'll be doing me a favour too - it's much easier to troubleshoot bugs when I can reproduce it on my side :)

How big are your files? If they are too big to e-mail (lcoombe@bcgsc.ca), you could put them on a google drive for me to download them from?

Let me know!
Lauren

**Comment by lcoombe** [comment]
Hi Priscila,

Thanks for the link to your assemblies - I have successfully downloaded your assemblies and can reproduce the issue on my end. I hope to have a fix for you sometime next week!

In the meantime, a workaround would be to turn the overlap detection off (`overlap=False`) - it looks like that is where the code is failing. Basically, in this case, if sequences to be joined overlapped, they will be joined end-to-end (with a gap in-between), as opposed to attempting to trim the overlapping sequence. That was how earlier versions of ntJoin worked - the overlap feature was introduced in v1.1.0.

Thanks!
Lauren

**Comment by lcoombe** [comment]
Hi Priscila,

Thanks again for the assemblies - it was very helpful for me to sort out where the issue was coming from.

It turns out that some of the sequences in your target fasta file have terminal N's - or N characters at the beginning and/or end of the sequences. That's not compatible with ntJoin - so you'll need to strip those stray characters from the terminal ends of the sequences before running ntJoin.
You can do that with a fairly straightforward perl one-liner:
```
seqtk seq FlyePolishedRedundansPurgeDups.BlobT.noProk.fasta |perl -ne 'chomp; if(/^>/){print "$_\n";} else {$seq=$_; $seq =~ s/^N+|N+$//gi; print "$seq\n";}' > FlyePolishedRedundansPurgeDups.BlobT.noProk.no-term-Ns.fasta
```

I'll add a note to the README about that to help future users.

Thanks again for reporting this issue and for your patience as we sorted it out!
Lauren

**Comment by psal591** [comment]
Hi Lauren,

You were most kind with your time and knowledge, and thank you for helping
me figure out how I can use ntJoin in my assemblies, it is most appreciated.

Best,

Priscila.

**Comment by lcoombe** [comment]
You are very welcome! Feel free to open another issue if you have any other problems or questions :)
