### ISSUE TITLE
Invalid IUPAC characters 

### ISSUE THREAD

**Issue by Kaiden-exe** [bcgsc/ntJoin#111]
Hello, I installed ntJoin using conda and I was trying it out, but I keep getting this error: 

```
ntjoin/bin/share/ntjoin-1.0.5-0/src/indexlr --long --pos -k 32 -w 1000 -t 5 ref.fasta > ref.fasta.k32.w1000.tsv
[2024-07-03 14:17:41] [ERROR] A sequence contains invalid IUPAC character
```

I have checked the reference fasta (it only has one sequence) and it only contains ATGC, except for the header, which starts with the '>' followed by an ID. The sequence is completely in uppercase as well. Any idea why it is throwing this error? Thank you in advance!

**Comment by warrenlr** [comment]
possible that `ref.fasta` is not in unix format?   A utility like dos2unix or running this one-liner at the terminal may help `cat ref.fasta | perl -ne 's/\r\n/\n/g;print "$_";' `

FYI - Our main developer is away on vacation, it may take some time in getting back to you. Thank you for your interest in ntJoin

**Comment by Kaiden-exe** [comment]
Hello Warren, thank you so much! That worked. It is now telling me that `"File 'assemble' does not exist."` and `"File 'check_params' does not exist."`

The full traceback is: 
```
Reading makefiles...
Updating makefiles....
Updating goal targets....
 File 'assemble' does not exist.
   File 'check_params' does not exist.
  Must remake target 'check_params'.
  Successfully remade target file 'check_params'.
  File 'ref.fasta.k32.w1000.tsv' does not exist.
 Must remake target 'ref.fasta.k32.w1000.tsv'.
```

Should I make a separate issue for this?

**Comment by warrenlr** [comment]
I'm curious, did you run the ntJoin demo? If not, I recommend starting there and making sure you follow the steps closely, especially when migrating to using your own data.

Sure, a new issue makes sense to me. I'll close this one.  (For posterity: original Issue related to DOS formatting -- Resolved)
