### ISSUE TITLE
File assemble / check_params does not exist 

### ISSUE THREAD

**Issue by Kaiden-exe** [bcgsc/ntJoin#112]
Hello I am trying to run the conda installation of ntJoin and it gets stuck after this message

```
Reading makefiles...
Updating makefiles....
Updating goal targets....
 File 'assemble' does not exist.
   File 'check_params' does not exist.
  Must remake target 'check_params'.
  Successfully remade target file 'check_params'.
  File 'ref.fasta.k32.w1000.tsv' does not exist.
 Must remake target 'ref.fasta.k32.w1000.tsv'.
/anaconda3/envs/ntjoin/bin/share/ntjoin-1.0.5-0/src/indexlr --long --pos -k 32 -w 1000 -t 5 ref.fasta > ref.fasta.k32.w1000.tsv
```

I have run the test-installation.sh script successfully (in the same environment) and the output seemed to match the files in the expected output folder. My reference sequence is in 2-line fasta format and is present in the working directory. Any ideas on what is going wrong and how I can resolve this? Thank you in advance!

**Comment by warrenlr** [comment]
could you also paste your ntJoin command? thanks!

**Comment by Kaiden-exe** [comment]
Yes, sorry for not including it before. 

`ntJoin assemble target=contigs.fasta target_weight=1 references='ref.fasta' reference_weights='2' prefix=scaf-test t=5`

the contigs.fasta file is in the same format as the ref.fasta file, which have both been converted using dos2unix.

**Comment by warrenlr** [comment]
Could you please run without specifying t=5 (it will use 4 threads by default)

Also, since the demo worked well in your hands, using the exact same command/params, but replacing the target and reference would be the next logical step to troubleshoot the failure

**Comment by Kaiden-exe** [comment]
Hi thank you for the hint! It was indeed the thread usage. The exact same command without t=5 does run. I did a quick test with the threads and 1-4 works fine, but anything higher than that gives the error as described above. Thank you for your help!

**Comment by warrenlr** [comment]
My pleasure, @Kaiden-exe, I'm glad it helped!
Thank you for your interest in ntJoin, and using our tool in your research,
Rene
