### ISSUE TITLE
Error: No module named 'packaging'

### ISSUE THREAD

**Issue by desmodus1984** [bcgsc/ntJoin#117]
Hi,

I installed ntJoin using conda. I thought it would work, but it failed when I tried running it with this code:
`ntJoin assemble target=myse-hapog.fasta target_weight=1 references='myse_female.fasta' reference_weights='2' k=32 w=500`

I am in the directory, where all the files are, and I changed the names of the example code, and I got this error:
ntJoin assemble target=myse-hapog.fasta target_weight=1 references='myse_female.fasta' reference_weights='2' k=32 w=500
/home/juaguila/miniconda3/envs/long-assembly/bin/share/ntjoin-1.1.5-0/bin/ntjoin_run.py -p out.k32.w500.n1 -n 1 -s myse-hapog.fasta.k32.w500.tsv -l 1 \
-r "2" -k 32 -g 20 -G 0 -t 1 --overlap --overlap_gap 20 --btllib_t 4 --overlap_k 15 --overlap_w 10 myse_female.fasta.k32.w500.tsv
Traceback (most recent call last):
  File "/home/juaguila/miniconda3/envs/long-assembly/bin/share/ntjoin-1.1.5-0/bin/ntjoin_run.py", line 8, in <module>
    from ntjoin_assemble import NtjoinScaffolder
  File "/home/juaguila/miniconda3/envs/long-assembly/bin/share/ntjoin-1.1.5-0/bin/ntjoin_assemble.py", line 17, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
make: *** [/home/juaguila/miniconda3/envs/long-assembly/bin/share/ntjoin-1.1.5-0/ntJoin:229: myse-hapog.fasta.k32.w500.n1.assigned.scaffolds.fa] Error 1

I even installed all the requirements and it didn't work.

Hope this error can be fixed.

Thanks;

**Comment by lcoombe** [comment]
Hi @desmodus1984,

Could you try:
`conda install -c conda-forge packaging`

I thought that the `packaging` module was installed by default with the other dependencies (I have never had an issue when installing ntJoin via conda), but perhaps not always. 
If that works for you, I'll make sure to update the conda recipe and requirements.txt

**Comment by lcoombe** [comment]
packaging added to dependencies for conda recipe in https://github.com/bioconda/bioconda-recipes/pull/50766
