### ISSUE TITLE
Question: How stable is ntJoin?

### ISSUE THREAD

**Issue by enormandeau** [bcgsc/ntJoin#20]
I'm looking for genome scaffolding using the info of other high-quality genomes. I like how ntJoin looks so far.

- How mature/stable would you say ntJoin is at this point?
- What big changes are likely to occur in the coming months?

Thanks!

**Comment by lcoombe** [comment]
Hi @enormandeau,

Yes, ntJoin is both mature and quite stable right now - The latest release was used for the experiments in our ntJoin preprint (https://www.biorxiv.org/content/10.1101/2020.01.13.905240v1.article-metrics).

At this time, we don't have any major changes to the current scaffolding functionality planned. We're always open to feature requests, though.

Thanks for you interest in ntJoin!
Lauren

**Comment by enormandeau** [comment]
Thank you! I will definitely try ntJoin :)
