### ISSUE TITLE
Make error after successful instalation

### ISSUE THREAD

**Issue by ViriatoII** [bcgsc/ntJoin#22]
Hey,

I have this error:

`make: *** No rule to make target `B73v4.txt', needed by `B73v4.txt.k30.w1000.tsv'.  Stop.`

When trying to run my command after a successful installation from source:

```
$ntJoin assemble target="../assemblies/myassembly" \
	references="B73v4.txt" \
	reference_weights="1" \
	t=12 k=30
```

What's wrong? Do you think I should reinstall?

**Comment by lcoombe** [comment]
Hi @ViriatoII,

Are both your assembly and reference in fasta format? 
Are you using the most recent commit in the repo? Previously, ntJoin expected both the target and the reference(s) to have the `.fa` suffix, but I made a fix earlier this week that should allow any suffix.

Also, the target assembly and reference files all need to be in the current working directory - so you could make a soft link to your assembly before running the ntJoin command:
```
ln -s ../assemblies/myassembly myassembly.fa
```

Hope that helps!
Lauren

**Comment by ViriatoII** [comment]
Ok, thanks!  Yeah, that was the problem. 

Maybe the program could give an error message saying that references must be in the same directory? 

Cheers,
Ricardo

**Comment by lcoombe** [comment]
Glad you got it working! I've added a note about the files needing to be in the working directory to the README and the help page. I'll look into adding some error checking in the `ntJoin` makefile as well.
Thank you for your interest in ntJoin!
