### ISSUE TITLE
Adding sequence from the reference into gaps

### ISSUE THREAD

**Issue by Tierhon** [bcgsc/ntJoin#28]
Hi,
thank you for this nice tool. It does almost exactly what I want. 

I have two different assemblies based on the same dataset (from two different assemblers). They are quite different, and by using one of them as a reference I get a nice conciliation. However, the reference do have sequence that could be added into the gaps of the target. Is it easy to add an option to fill those gaps? 

I know I could use another tool (but I don't know exactly which, few does this), but here you have the coordinates of the reference so it should be easy to put whatever is in the reference in those coordinates instead of just Ns.

Thank you.

Ole

**Comment by lcoombe** [comment]
Hi Ole,

That's an interesting suggestion! In terms of implementation, it wouldn't be a completely trivial feature, but is certainly possible.

I guess there's a couple of considerations when thinking about adding a feature that would allow filling in gap sequences:
* It would probably have to be limited to when a single reference is supplied (it would get more tricky if multiple references are used) and the `no_cut=True` option is not used
* The gap sequence filled in would have to be 'approximate' -- Basically we know the positions of the minimizers in common with ctgA and ctgB, but not exactly where the end of the contigs and the reference line up, as a lightweight minimizer mapping is used as opposed to alignments (See Supplementary Table 3 from the paper for a visual of this). So my concern would be that the gap sequence added in might have coordinates that are off a bit if the reference and target have any indels, which could artificially introduce deletions or insertions when filling the gap (and is possible even when assembling the same data). 
* It would really only be useful for a case like yours, where the assemblies are of the same data/individual -- I wouldn't recommend filling in gap from reference sequences in the general case.

I'd be interested to hear your thoughts - Thank you for your interest in ntJoin!
Lauren

**Comment by Tierhon** [comment]
Hi Lauren.

I agree that this can only be limited to when a single reference is used. Otherwise it would be non-trivial to insert the sequence (from one reference, or consensus of several, what if gap lengths differ a lot, etc). 

You second point is unfortunate. I know that the two different haplotypes in my organism is quite different, but not exactly how different. There will certainly be indels between them. My specific case is that I have done both Falcon-Unzip and Flye assemblies, and I know that there are sequence in the Flye assembly not captured at all with the Falcon assembly. However, I see the value of separating haplotypes (as Falcon-Unzip does) and I am looking at ways of inserting the sequences from the Flye assembly together with the primary contigs. 

I have tried Ragoo, but there are no exact gap sizes there (and gaps are certainly larger than 20 or 100 or 500 bp, the largest I have seen from ntJoin is 600 kbp and I think that is real). I have not tried Ragout, since I cannot get Cactus up and running on my system. 

Ideally, I would like alignments, but no tools seem to implement it properly. And I would rather not hack away in unknown code base. I will do consensus by mapping PacBio reads back to the assembly, so that will hopefully fix some putative issues. 

I agree with you last point. Combining sequences from different individuals is not a good approach, certainly not when the species has a lot of genetic diversity (birds, fish, microbes).

Thank you.

Ole

**Comment by lcoombe** [comment]
Hi Ole,

One approach you could potentially take is running ntJoin to do the scaffolding quickly and alignment-free, then fill gaps with Cobbler (https://github.com/bcgsc/rails) - This is a tool that uses alignments of long sequences (of any origin) to fill in gap sequences. I do agree that in this particular case where you want to fill in the gap sequence, perhaps read alignments are better suited than minimizers for gap-filling.
If it became helpful for you in the future, what I could possibly do is have an optional output file that includes the reference ID (for each assembly, if applicable) that supported each output join? I'm thinking then you could potentially come up with a targeted gap-filling approach with Cobbler, although that would require some scripting, and I agree it is best to stick to known code!

Hope that helps,
Lauren

**Comment by Tierhon** [comment]
Hi Lauren,
thank you for your suggestion. However, I've got a couple of 100 gaps that are longer than abot 30 kbp, with several longer than 100 kbp. There is certainly something really interesting going on in the differences between these two assemblies. I am not sure if Cobbler can help filling those long gaps. 

The optional output file could be useful, but I might just infer it from minimap2 mappings. 

The most important aspect here is the scaffolding. As long as I can trust it, I could do some gap-filling myself (get coordinates of gaps and which sequence map confidently to each side of it for instance). 

How can I run ntJoin so I can be sure that the amount of misjoins is at a minimum? It seems to vary depending on what kind of species it is being applied to. 

Thank you.

**Comment by lcoombe** [comment]
Hi Ole,

Theoretically, the gap size shouldn't matter to Cobbler, it just needs to have a long sequence that is able to have good anchoring alignments on either side of the gap -- but of course there are no guarantees, so you'd have to try it out to see how well it worked for you! 

When I'm doing runs (whether it be human, frog, conifers), I find that k=32, w=500 tends to work well for most datasets, so I'd suggest starting there.
