### ISSUE TITLE
make error using a container for ntJoin

### ISSUE THREAD

**Issue by drashwinelkar** [bcgsc/ntJoin#32]
I love this tool as it does exactly what I want.
I am using two containers for ntJoin from biocontainers.pro 
quay.io/biocontainers/ntjoin:1.0.1--py37he513fc3_0
quay.io/biocontainers/ntjoin:1.0.1--py36he513fc3_0

while using both I get the make error : 
command time -v -o Ctet_49205_Harvard.fa.k32.w500.tsv.time /usr/local/bin/share/ntjoin-1.0.1-0/src/indexlr --pos -k 32 -w 500 -t 2 Ctet_49205_Harvard.fa > Ctet_49205_Harvard.fa.k32.w500.tsv
time: invalid option -- 'o'

Any idea why?
I used containers because I am not well versed with installing all the background requirements etc. 
I had hoped (somewhat naively) that a container should not have these problems.
Can you suggest why this is happening?

**Comment by lcoombe** [comment]
Hi @drashwinelkar,

Interesting -- the docker containers are built automatically from the bioconda recipe, so I actually haven't tried them out yet. I can reproduce your issue -- it looks like the `time` available in the container is quite different from what I've seen in the past, so doesn't have a `-o` option. 
A workaround here should be to specifically set the `time` variable in your `ntJoin` command. For example: `time=time` or `time= `. The former will just output the time of each step in your standard error, and the latter will just clear out that variable so no time metrics will be done.

Also, just a heads-up that there is a 1.0.2 release available on biocontainers, in case you want to use the latest release.

Thanks for your interest in ntJoin -- I hope that helps!
Lauren

**Comment by drashwinelkar** [comment]
Hi lcoombe
Thanks for your very prompt reply! Yes that fixes the issue. but now I get the following error:
make: *** No rule to make target 'Ctet_49205_Harvard.fasta.k70.w1000.tsv', needed by 'assemble'.  Stop.
So I run the same command in the container and in the version I installed using brew.
It works on the brew version and does not in the container. I will try the latest version of the same. Thanks a lot for your help!

**Comment by lcoombe** [comment]
Hi @drashwinelkar,

Great, I'm glad that fixed the `time` issue!

For the container vs. brew -- I'm guessing it is due to using release 1.0.1 vs the latest 1.0.2 (If you are using the same containers that you have in your original comment). Between release 1.0.1 and 1.0.2, I updated the code to allow input fasta files with any file extension, vs. before it required `.fa` as the suffix. So yes, that issue should be fixed if you use the latest release for the container! The most current release (v1.0.2) is in homebrew and bioconda.
