### ISSUE TITLE
failure to install from git

### ISSUE THREAD

**Issue by drashwinelkar** [bcgsc/ntJoin#33]
I tried to install from the git source following the instructions.
I ensured that I have all the dependencies from python3 as well as zlib and the correct version of bedtools and samtools
however when I run the command make
all I get is:
 g++ -g -O3 -Wall -Werror -Wno-error=unknown-pragmas -std=c++11 -pthread -I./include -I./vendor    indexlr.cc  -lz -o indexlr
with no output after this
it reverts back to command line
I assumed the installation went through so did a test_installation.sh as per the instructions and I get  
./test_installation.sh: line 9: ntJoin: command not found
This means the installation hasn't happened. So any idea what has gone wrong because the make does not give any error

**Comment by lcoombe** [comment]
Hi @drashwinelkar,

Have you ensured that the path to your git repo (`/path/to/ntJoin_git_repo`) is on your PATH?
The shell script looks for the makefile `ntJoin`, so if you you are in the `tests` directory and the path to the main folder for ntJoin isn't on your PATH it would error out. You could run `echo $PATH` to double check.

Hope that helps, and thanks for your interest in ntJoin!
Lauren

**Comment by drashwinelkar** [comment]
Yes that fixed it! Thanks for the very fast answer.
Also I installed from brew in the meantime and it works like a charm!
This tool you have made is fantastic! Thanks for that.

**Comment by lcoombe** [comment]
I'm glad that worked, and it's so great to hear that you're finding ntJoin useful! :)
