### ISSUE TITLE
 time: command not found... Error 127

### ISSUE THREAD

**Issue by sadikmu** [bcgsc/ntJoin#38]
Hi thanks a lot for this nice tool.

I am getting the following error message and could not able to figure what I have missed here. 

```
`
ntJoin assemble \
target=target.fasta \
target_weight=1 \
references=reference.fasta \
reference_weights=2 \
prefix=out.int \
k=32 w=1000
`
```

std.out
```
`
command time -v -o reference.fasta.k32.w1000.tsv.time /home/miniconda/envs/ntjoin/bin/share/ntjoin-1.0.3-0/src/indexlr --pos -k 32 -w 1000 -t 4 reference.fasta > reference.k32.w1000.tsv
bash: time: command not found
make: *** [/home/miniconda/envs/ntjoin/bin/share/ntjoin-1.0.3-0/ntJoin:154: reference.fasta.k32.w1000.tsv] Error 127
make: *** Deleting file 'reference.fasta.k32.w1000.tsv'
```
`
Any suggestions please?

Thanks

**Comment by lcoombe** [comment]
Hi @sadikmu,

Sorry for the delayed response -- I was on vacation last week.

This error looks similar to the one reported in #32 - It looks like the command `time` isn't found on your system? Try setting the `time` variable to a time command that you do have available on your system (`/usr/bin/time`? `gtime`?), or you could also try  `time= `. The latter should clear out the `time` variable so it doesn't try running any timing of the commands.

I hope that helps and thanks for your interest in ntJoin!
Lauren
