### ISSUE TITLE
ntJoin command time -v -o 

### ISSUE THREAD

**Issue by azrasid** [bcgsc/ntJoin#39]
HI,
I am running ntJoin and getting this error

[azra@n14 ABYSS]$ ntJoin assemble target=ind78-scaffolds.fa target_weight=1 references=/home/azra/Simulation/genes/cyp2c19/blast_scaffolds/cyp2c19ref.fa reference_weights=‘2’ 

command time -v -o /home/azra/Simulation/genes/cyp2c19/blast_scaffolds/cyp2c19ref.fa.k32.w1000.tsv.time /opt/exp_soft/bioinf/bin/src/indexlr --pos -k 32 -w 1000 -t 4 /home/azra/Simulation/genes/cyp2c19/blast_scaffolds/cyp2c19ref.fa > /home/azra/Simulation/genes/cyp2c19/blast_scaffolds/cyp2c19ref.fa.k32.w1000.tsv
time: cannot run /opt/exp_soft/bioinf/bin/src/indexlr: No such file or directory
make: *** [/home/azra/Simulation/genes/cyp2c19/blast_scaffolds/cyp2c19ref.fa.k32.w1000.tsv] Error 127
make: *** Deleting file `/home/azra/Simulation/genes/cyp2c19/blast_scaffolds/cyp2c19ref.fa.k32.w1000.tsv’
[azra@n14 ABYSS]$

Please help me with this error.

Thanks

**Comment by lcoombe** [comment]
Hi @azrasid,

How did you install ntJoin? If you installed from source, then you need to make sure that you compiled the indexlr code: https://github.com/bcgsc/ntJoin#installing-ntjoin-from-the-source-code

Also, make sure that all of your files are in your current working directory, instead of specifying absolute paths. You can make soft links to ensure the program sees the files in the current working directory. Thus, your command would be:
```
ntJoin assemble target=ind78-scaffolds.fa target_weight=1 references=cyp2c19ref.fa reference_weights=‘2’
```

I hope that helps - thank you for your interest in ntJoin!
Lauren

**Comment by azrasid** [comment]
I really appreciate your quick response.
Thanks

**Comment by azrasid** [comment]
Hi,
Everything related to ABYSS is on cluster and the input files is in the same directory. when I ran the command 

**[azra@n06 ABYSS]$ ntJoin assemble target=ind78-scaffolds.fa target_weight=1 references=cyp2c19ref.fa reference_weights=‘2’**

I am getting this.

command time -v -o cyp2c19ref.fa.k32.w1000.tsv.time /opt/exp_soft/bioinf/bin/indexlr --pos -k 32 -w 1000 -t 4 cyp2c19ref.fa > cyp2c19ref.fa.k32.w1000.tsv
command time -v -o ind78-scaffolds.fa.k32.w1000.tsv.time /opt/exp_soft/bioinf/bin/indexlr --pos -k 32 -w 1000 -t 4 ind78-scaffolds.fa > ind78-scaffolds.fa.k32.w1000.tsv
command time -v -o ind78-scaffolds.fa.k32.w1000.n1.assigned.scaffolds.fa.time /opt/exp_soft/bioinf/bin/ntjoin_assemble.py -p out.k32.w1000.n1 -n 1 -s ind78-scaffolds.fa.k32.w1000.tsv -l 1 \
-r “2” -k 32 -g 20 -G 0 -t 1 -m 90 cyp2c19ref.fa.k32.w1000.tsv
Traceback (most recent call last):
 File “/opt/exp_soft/bioinf/bin/ntjoin_assemble.py”, line 17, in <module>
  import igraph as ig
 File “/opt/exp_soft/python37/lib/python3.7/site-packages/igraph/__init__.py”, line 8, in <module>
  raise DeprecationWarning(“To avoid name collision with the igraph project, ”
DeprecationWarning: To avoid name collision with the igraph project, this visualization library has been renamed to ‘jgraph’. Please upgrade when convenient.
make: *** [ind78-scaffolds.fa.k32.w1000.n1.assigned.scaffolds.fa] Error 1
[azra@n06 ABYSS]$

Is it an error or can I ignore it

**Comment by lcoombe** [comment]
Hi @azrasid,

What version of `python-igraph` are you using? Is it possible that you installed `igraph` instead? I haven't seen this error myself before, but it looks similar to one reported here at StackOverflow: https://stackoverflow.com/questions/36200707/error-with-igraph-library-deprecated-library

**Comment by azrasid** [comment]
Thanks Lauren.
I will update and see.

**Comment by azrasid** [comment]
Apologies to bug you again.
this time the ntJoin command ran nicely - but this line at the end. Below is the snippet of what I got when I ran the command.

Total number of components in graph: 1 

2020-10-06 17:37:47.908284 : Printing output scaffolds
2020-10-06 17:37:47.999333 : DONE!
touch ind78-scaffolds.fa.k32.w1000.n1.unassigned.scaffolds.fa
command time -v -o ind78-scaffolds.fa.k32.w1000.n1.all.scaffolds.fa.time cat ind78-scaffolds.fa.k32.w1000.n1.assigned.scaffolds.fa ind78-scaffolds.fa.k32.w1000.n1.unassigned.scaffolds.fa > ind78-scaffolds.fa.k32.w1000.n1.all.scaffolds.fa
[azra@n02 ABYSS]$

Is it OK like this.
Or do I still need to update something.

Many thanks in advance

**Comment by lcoombe** [comment]
Hi @azrasid ,
Yup - based on that snippet of the log, the run looks good to me!
If you ever wanted to double check that your installation is running properly, you could also run the script mentioned in the README here: https://github.com/bcgsc/ntJoin#testing-your-installation

**Comment by azrasid** [comment]
Thanks for being with me throughout my ntJoin journey.

Best Wishes

**Comment by lcoombe** [comment]
No worries! Glad I could help :)
