### ISSUE TITLE
Error - reference.fa source file is in invalid format!

### ISSUE THREAD

**Issue by eriled** [bcgsc/ntJoin#46]
Hi,
I get this error message when I try to run ntJoin.
ntJoin assemble t=4 target=Bullfinch_hybrid.fa target_weight=1 references='ZFtoplevel_unmask.fa' reference_weights='2' k=32 w=1000
command time -v -o ZFtoplevel_unmask.fa.k32.w1000.tsv.time /cluster/home/ericale/ntJoin/src/indexlr --pos -k                                    32 -w 1000 -t 4 ZFtoplevel_unmask.fa > ZFtoplevel_unmask.fa.k32.w1000.tsv
[ERROR] ZFtoplevel_unmask.fa source file is in invalid format!
make: *** [ZFtoplevel_unmask.fa.k32.w1000.tsv] Error 1
make: *** Deleting file `ZFtoplevel_unmask.fa.k32.w1000.tsv'

I tried a different reference and I had the same result. (I also tried removing the quotes).
The reference file looks like this:
>HG009209.1 dna_sm:primary_assembly primary_assembly:SCA1:HG009209.1:1:88717973:1 REF
CCCATGGAGGACATGGGGCTGAGGTGGGGACACGGGGCTGTCCCTGCTGTCCCCAGCGGG
GTGTGGGGTTGGGATGGGCACACAGGAgtccctgctgtccctgctgtccctcctgtcccc

or
>1 dna:primary_assembly primary_assembly:bTaeGut1_v1.p:1:1:114557415:1 REF
AAGCCAGCCATATCAGTATCCCAGCCGCGCAGGATCTGAGCGCCACCCAGCAATGGCCAG
CCACTATGTGTGCCCCTGTATCACTGGAATTCAAGGCCCACCACCCTGTTCTCAGCCATA

I thought that it may be due to the soft masking in the first one, and then tried an unmasked reference.
Both of them are just downloaded reference files from Ensembl.

I did have issues installing and had help from the server help desk this was how it was installed:
$ python -m venv ntjoin-venv
$ source ntjoin-venv/bin/activate
$ pip install pybedtools python-igraph pymannkendall
$ git clone https://github.com/bcgsc/ntJoin.git
$ cd ntJoin/src
$ make
$ export PATH=$PATH:/cluster/home/$USER/ntJoin

I would appreciate any help as I would really like to try this software.
Thanks,
Erica

**Comment by lcoombe** [comment]
Hi Erica,

It looks like you are missing the conventional `>` character on the header lines of your reference file? Or maybe it's just how the comment formatted? The program is expecting the reference (and target assembly) in [fasta format](https://en.wikipedia.org/wiki/FASTA_format), so is expecting each header line in the file to begin with that character. Also, I can't tell from the formatting if your fasta file is a multi-line fasta file, but make sure that you have two lines per entry (ie. the sequence is fully on a single line with no line breaks). I use `seqtk` to do this easily: `seqtk seq my_assembly_with_newlines.fa > my_assembly_two_lines_per_entry.fa`

Ie this would be a valid entry (Notice the `>` and that the sequence is all on one line):
```
>1 dna:primary_assembly primary_assembly:bTaeGut1_v1.p:1:1:114557415:1 REF
AAGCCAGCCATATCAGTATCCCAGCCGCGCAGGATCTGAGCGCCACCCAGCAATGGCCAGCCACTATGTGTGCCCCTGTATCACTGGAATTCAAGGCCCACCACCCTGTTCTCAGCCATA
```

Your installation process looks fine! Some users find it easier to use `conda` or `brew` to install, but totally fine to compile from the source code as well.

Hope that helps - Thanks for your interest in ntJoin!
Lauren

**Comment by eriled** [comment]
Hi,
It is a valid fasta file (I have used it for other things with no problems)- it is just the way it appeared here, but it is a multiline fasta. I will fix that and try again.

Thanks,
Erica

**Comment by lcoombe** [comment]
Ah ok - must have just been how github auto-formatted your example entries that I couldn't see the `>`. Yes, let me know if removing those newlines in the sequences does the trick!

Best,
Lauren

**Comment by eriled** [comment]
Hi,
This works fine now and this software is very useful for me - Thanks very much. Maybe this one-line fasta format should be mentioned in the documentation since a lot of reference genomes (e.g. from Ensembl and Genbank) are multi-line when downloaded.
Best wishes,
Erica

**Comment by lcoombe** [comment]
Hi Erica,

I'm glad that fixed the issue, and that ntJoin is working well for you!
Yes, you make a good point about the documentation -- I've added a note about the single-line fasta format requirement to the documentation in b0ce5fb.

Best,
Lauren
