### ISSUE TITLE
Input file Error

### ISSUE THREAD

**Issue by ardy20** [bcgsc/ntJoin#55]
Dear All

I used conda to run ntJoin but I got the following input file problem while running ntJoin:

server@fl002:/30days/ntJoin> ntJoin assemble target=1L_final.p_F_ctg.fa target_weight=1 references='list.fa' reference_weights='2' k=32 w=500 t 18
/30days/ntJoin/bin/share/ntjoin-1.0.5-0/src/indexlr --long --pos -k 32 -w 500 -t 4 list.fa > list.fa.k32.w500.tsv
[2020-12-23 15:17:01] [ERROR] list.fa source file is in invalid format!
make: *** [/30days/uqakhara/ntJoin/bin/share/ntjoin-1.0.5-0/ntJoin:163: list.fa.k32.w500.tsv] Error 1
make: *** Deleting file 'list.fa.k32.w500.tsv'

I do not how to prepare the input fasta files. I already changed my multiline fasta to single line uisng the awk command as follow: awk '/^>/ {printf("\n%s\n",$0);next; } { printf("%s",$0);}  END {printf("\n");}' < file.fa

But still the same problem. What the problem might be?

Regards
Ardy

**Comment by warrenlr** [comment]
thank you for your message & interest in ntJoin, Ardy.

Just wondering, did you try without quotes:

eg.
```
ntJoin assemble target=qry.fa target_weight=1 references=ref.fa reference_weights=2 k=32 w=250 n=1 t=4 no_cut=True
```

A possible format issue may be related to DOS and new line characters. If you didn't generate ref.fa on a unix system, I encourage you to run dos2unix (or a PERL one-liner `perl -pi -e's/\015\012/\012/g' ref.fa`) to convert to a unix format.

I hope this solves it.

Cheers,
Rene

**Comment by ardy20** [comment]
Hi Rene

I tried both methods but I still get the same error. My ref.fa is a chromosome level assembly including 41 scaffolds from Dovetail Omni-C.

[ERROR] jasmine-uni1535-mb-hirise-37a2i_11-18-2020__final_assembly.fa source file is in invalid format!
make: *** [/30days/ntJoin/bin/share/ntjoin-1.0.5-0/ntJoin:163: jasmine-uni1535-mb-hirise-37a2i_11-18-2020__final_assembly.fa.k32.w250.tsv] Error 1
make: *** Deleting file 'jasmine-uni1535-mb-hirise-37a2i_11-18-2020__final_assembly.fa.k32.w250.tsv'

**Comment by warrenlr** [comment]
and the ntjoin demo works as intended?

If so, there has to be something to do with the format of ref.fa .. take a look at the demo "ref.fa" to see what is different in the format.

**Comment by ardy20** [comment]
The ref.fa is like the format below but has 41 scaffolds:

>Scaffold_1__1_contigs__length_35828999
CCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAA
CCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAA

**Comment by ardy20** [comment]
It looks like this:

>Scaffold_1__1_contigs__length_35828999
CCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAA
CCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAA

**Comment by ardy20** [comment]
In Linux it has > and there is no gap but when I copy-paste here it looks like this.

**Comment by ardy20** [comment]
This time I tried the test files and got this error:

/gpfs1/scratch/30days/ntJoin/bin/share/ntjoin-1.0.5-0/src/indexlr --long --pos -k 32 -w 250 -t 4 ref.fa > ref.fa.k32.w250.tsv
/gpfs1/scratch/30days/ntJoin/bin/share/ntjoin-1.0.5-0/src/indexlr --long --pos -k 32 -w 250 -t 4 scaf.f-f.fa > scaf.f-f.fa.k32.w250.tsv
samtools faidx ref.fa
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
make: *** [/30days/ntJoin/bin/share/ntjoin-1.0.5-0/ntJoin:166: ref.fa.fai] Error 127

**Comment by lcoombe** [comment]
Hi @ardy20,

As Rene mentioned, for this error that you are getting:
```
[ERROR] jasmine-uni1535-mb-hirise-37a2i_11-18-2020__final_assembly.fa source file is in invalid format!
```
That indicates that there is something wrong with the format of that fasta file. Can you double check that you properly converted from multi-line fasta to single line fasta (ie. sequences fully on one line) for all input fasta files? I use `seqtk seq` for this. From the comment with sequence `Scaffold_1__1_contigs__length_35828999`, that sequence appears to still have newlines in the sequence?

For the samtools error, that is an issue with your samtools installation. I'm not sure how you installed it, but try re-installing on whichever package manager you used or from the source code.

Lauren

**Comment by ricardo-aaron** [comment]
I'm having the same "file is in invalid format!" problem. It appears the problem is that ntJoin does not accept wrapped fasta files, it will only accept fasta files where the sequence is in a single line. Which is a strange behavior since wrapped fasta is supposed to be the standard (or so I thought).

**Comment by lcoombe** [comment]
Hello @ricardo-aaron,

Yes, your input fasta file needs to be in the single line fasta format (vs. having new-line breaks) - like we mention in the help documentation (https://github.com/bcgsc/ntjoin#usage) 

In my experience, it's not uncommon for tools to only work with single-line fasta formats, which is what I always work with myself. Luckily, it's really easy to convert a multi-line fasta to a single-line fasta - I use `seqtk seq` myself.

Hope that helps!
Lauren
