### ISSUE TITLE
Separate assigned + unassigned scaffolds

### ISSUE THREAD

**Issue by lcoombe** [bcgsc/ntJoin#6]
Update output so that it separately outputs the assigned scaffolds (ie. those put into a path by ntJoin) and unassigned scaffolds (those NOT put into a path by ntJoin)

**Comment by gchaput19** [comment]
Hi @lcoombe, just want to make sure I am understanding the output correctly. Is the "assigned" what we should use for further downstream analysis? For example, I have an assembly of many bacterial species. I have the full set of reads as my query and then subset assemblies of the same reads that I am using as references. Goal is to capture some of the rarer bacterial isolates by having subset assemblies. Should I use the "all" for binning step or "assigned" for the binning step? Thanks so much in advanced!

**Comment by lcoombe** [comment]
Hi @gchaput19,

For downstream analysis, I generally suggest using the "all" file. Basically, the "assigned" file contains all the scaffolds generated by the ntJoin reference-guided scaffolding, and the "unassigned" has all the input contig sequences that weren't assigned to a scaffold. The "all" is just a concatenation of these, which retains all the sequence information from the input assembly. 

Hope that makes sense!
