### ISSUE TITLE
ntJoin:test error

### ISSUE THREAD

**Issue by guanttttt** [bcgsc/ntJoin#64]
Hello!
when I use the command to test my ntJoin installation: 
1. i input "set -eux" in Linux,but there is nothing present, no echo "Running ntJoin..."
2. i run the second command"ntJoin  assemble target=scaf.f-f.fa target_weight=1 references='ref.fa' reference_weights='2' prefix=f-f_test k=32 w=1000" in the directory of tests, and there is a error of "ModuleNotFoundError: No module named 'igraph'"

these errors do confused me several days,please help,thanks!

**Comment by lcoombe** [comment]
Hello @guanttttt,

For (2), just to be sure, are you executing the following command in the `tests` directory?
```
./test_installation.sh 
```
If so, could you post the command + any following log messages from your terminal?

For (2), that means that you haven't installed the `python-igraph` module for the python version that you are using. Take another look at the [dependencies](https://github.com/bcgsc/ntJoin#dependencies) of ntJoin, and double check they are all installed successfully.

Hope that helps - thank you for your interest in ntJoin!
Lauren

**Comment by guanttttt** [comment]
thank you!！
 I have resolved the second problems, for the error of "No module named 'igraph'", that is some python modules i didn't install them before as you say (including python-igraph,pybedtools and pymannkendall)
now i run the command of "./test_installation.sh" in the test directory,  i got another error of "Error: malformed BED entry at line 1. Start was greater than end. Exiting.bedtools getfasta failed -- is bedtools on your PATH?"  But i have already installed the bedtools and add it in my PATH. When i run the command of"bedtools/bedtools getfasta", it will present the relevant information normally.

**Comment by guanttttt** [comment]
thank you! i have resolved these two problems. but there have another question about the reference file.
1. the reference file: in the supplementary table-S1-c.elegans-Bristol N2 reference
2. the target assembly : also in S1-c.elegans-AByss

and i got the error of `"[ERROR] GCF_000002985.6_WBcel235_genomic.fna source file is in invalid format!"`, i have tried to delete the line break in this file(make the sequence all on one line), or alter the `.fna` to `.fa `,but it's still not working.

**Comment by guanttttt** [comment]
hello @lcoombe 
i am so appreciate your quick reply! The relevant code is as follows:
1. this is the command that i used to launch ntJoin:
 `ntJoin assemble target=celegans-abyss.fa target_weight=1 references='result2.fna' reference_weights='2' k=32 w=500`

there have a contradiction that when i use the result2.fna, it present the error of `[ERROR] A sequence contains invalid IUPAC character: >` ,so i tried to delete the` >` in this file, and i got the error of `[ERROR] result1_no.fna source file is in invalid format!` , i don't know if it was my convert conde cause the data mess?

2. and this is my code about convert the fasta file:
```
def test():
    red = open("GCF_000002985.6_WBcel235_genomic_ref_ntJoin.fna", "r");
    wr = open("C.elegans\\result2.fna", "w");
    wr.truncate()
    contents = red.readlines()

    for line in contents:
        wr.write(line.strip('\n'))
    red.close()
    wr.close()

if __name__ == '__main__':
    test()

```

**Comment by guanttttt** [comment]
the convert code  will delete all of line breaks in  fasta file, so i would add an enter at the end of the first row.
just like: `>NC_003279.8 Caenorhabditis elegans chromosome Igcctaagcctaagcctaagcctaagcctaag...`  add an enter after 'I'

i also deal the data set of H_sapiens, it has the same error.

**Comment by lcoombe** [comment]
Hi @guanttttt,
It's possible that adding line breaks with 'enter' like that could be introducing unexpected characters. 
I'd suggest using `seqtk seq` to do the file conversion, since it's pretty easy to use and reliable. It's available on homebrew or conda if you're using those package managers.
Ie.
```
seqtk seq my_fasta.fa > my_fasta_without_breaks.fa
```

The demo ran fine for you, right? You could double check that your file formats are identical to those test files as well?

**Comment by guanttttt** [comment]
Hi @lcoombe 
You are soooooo cool!!!  I have completed a command run successfully! As you say, maybe my convert code does have some problems which could cause the data set didn't work, so i use the command of `seqtk seq` and it worked!

I am so appreciate your help! :)

**Comment by lcoombe** [comment]
@guanttttt - Yay!! I'm so glad you got it working! :D
