### ISSUE TITLE
[2021-07-19 21:34:27] [ERROR] strain-13-plasmid.txt source file is in invalid format!

### ISSUE THREAD

**Issue by ysawires12345678** [bcgsc/ntJoin#69]
Hello,
I'm trying to assemble plamisd contigs using a fully assembled reference sequence. all the files are in fasta format (just opened in notepad to verify the formate. all the files are in the same directory "bin" .
I ran this command "ntJoin assemble target= ABDU01.1-plasmid references='strain-13-plasmid.txt ,FDAARGOS_904_plasmid.txt ,FDAARGOS_903_plasmid.txt' reference_weights='2 1 1'"
and I got this message error"[2021-07-19 21:34:27] [ERROR] strain-13-plasmid.txt source file is in invalid format!
make: *** [/home/ysawires/miniconda3/bin/share/ntjoin-1.0.6-1/ntJoin:182: strain-13-plasmid.txt.k32.w1000.tsv] Error 1
make: *** Deleting file 'strain-13-plasmid.txt.k32.w1000.tsv'
Would you please and thank you be able to advise on this issue

**Comment by lcoombe** [comment]
Hi @ysawires12345678,

The error indicates that your input file(s) are not in the correct fasta format. You are using a non-standard suffix for your fasta files there (.txt usually being for normal text files), so start by using a standard suffix, such as `.fa`. Also, I see that you are using commas to separate some of the references? If that's part of the file names, that's OK, but remove them if not. Also, it may just be the formatting of the copied command, but looks like you have an extra space after `target=`

Hopefully that fixes it, but let me know - Thank you for your interest in ntJoin!
Lauren

**Comment by ysawires12345678** [comment]
Thanks for your response.
I removed the new  line breaks and it operated fine (I think). white one of the out put file would be the assembled sequence or there is further step?" is it ABDU01.1-plasmid.fa.k32.w1000.n1.assigned.scaffolds.fa"
regards
John

**Comment by ysawires12345678** [comment]
Thanks for your response.
I removed the new line breaks and it operated fine (I think). Which one of the out put files would be the assembled sequence or there is further step?" is it ABDU01.1-plasmid.fa.k32.w1000.n1.assigned.scaffolds.fa"
regards
John

**Comment by lcoombe** [comment]
Hi John,

Great! I'm glad that ntJoin is working for you now. 

The file with all the final sequences (either scaffolded or not) would be `ABDU01.1-plasmid.fa.k32.w1000.n1.all.scaffolds.fa`
The files `ABDU01.1-plasmid.fa.k32.w1000.n1.assigned.scaffolds.fa` and `ABDU01.1-plasmid.fa.k32.w1000.n1.unassigned.scaffolds.fa` are concatenated to that final file, so you don't lose any sequences in your assembly, even if they are not incorporated into a scaffold.
