### ISSUE TITLE
Translocation after scaffolding based on reference genome

### ISSUE THREAD

**Issue by wuxingbo1986** [bcgsc/ntJoin#70]
Hi Lauren,

I am scaffolding the contigs from ccs reads using a reference genome originally scaffolded by HiC. I then aligned the scaffolded genome back to the reference genome and see some translocations over several chromosomes. This two genomes is from the same species so this is kind of weird. Any ideas? The command and the dotplot are both here.

ntJoin assemble target=m54334U.ccs.asm.fa target_weight=1 references="primary_rev_rename_pmol.fasta" reference_weights="2" k=22 w=1000 g=100 G=100 no_cut=True agp=True

![Picture2](https://user-images.githubusercontent.com/68354053/127881719-b10479e7-2dc8-46b6-b172-76cf64fc0b5b.png)

**Comment by lcoombe** [comment]
Hi @wuxingbo1986,

At first glance, there are a few things here that could be coming into play:
- You are scaffolding an existing assembly, and not making any cuts with the options selected (which is fine!) - But that means that any misassemblies that are existing in the baseline assembly will be propagated to the post-ntJoin version. So errors that were minor pre-ntJoin would look much worse post-ntJoin.
- I don't know the details of your particular species, but for some species, it is expected for different individuals/strains/populations to have genomic rearrangements
- The k of 22, is lower than I usually use, particularly for assemblies with a higher base quality. It's possible that that is causing some more erroneous joins. I usually stick at 32, dropping as low as 24.

Those are my initial thoughts - I hope that helps!
Lauren
