### ISSUE TITLE
/ebio/abt3/nyoungblut/.zshenv:.:1: no such file or directory: /ebio/abt3/nyoungblut/.cargo/env

### ISSUE THREAD

**Issue by nick-youngblut** [bcgsc/ntJoin#85]
```
mamba install -p conda_env bioconda::ntjoin
```

```
ntJoin assemble target=target.fna target_weight=1 reference_config=refs.csv
```

Output:

```
/ebio/abt3/nyoungblut/.zshenv:.:1: no such file or directory: /ebio/abt3/nyoungblut/.cargo/env
/ebio/abt3/nyoungblut/.zshenv:.:1: no such file or directory: /ebio/abt3/nyoungblut/.cargo/env
/ebio/abt3/nyoungblut/.zshenv:.:1: no such file or directory: /ebio/abt3/nyoungblut/.cargo/env
/ebio/abt3/nyoungblut/.zshenv:.:1: no such file or directory: /ebio/abt3/nyoungblut/.cargo/env
/ebio/abt3/nyoungblut/.zshenv:.:1: no such file or directory: /ebio/abt3/nyoungblut/.cargo/env
/ebio/abt3/nyoungblut/.zshenv:.:1: no such file or directory: /ebio/abt3/nyoungblut/.cargo/env
/ebio/abt3/nyoungblut/.zshenv:.:1: no such file or directory: /ebio/abt3/nyoungblut/.cargo/env
/tmp/global2/nyoungblut/code/dev/tmp/genome_embed/ntJoin/conda_env/bin/share/ntjoin-1.0.8-1/src/indexlr --long --pos -k 32 -w 1000 -t 4 GCF_001652705.1_ASM165270v1_genomic.fna > GCF_001652705.1_ASM165270v1_genomic.fna.k32.w1000.tsv
/ebio/abt3/nyoungblut/.zshenv:.:1: no such file or directory: /ebio/abt3/nyoungblut/.cargo/env
/ebio/abt3/nyoungblut/.zshenv:.:1: no such file or directory: /ebio/abt3/nyoungblut/.cargo/env
[...]
```

`ntJoin assemble` finishes successfully, but there are ~50 of the `/ebio/abt3/nyoungblut/.zshenv:.:1: no such file or directory: /ebio/abt3/nyoungblut/.cargo/env` warnings/error sduring the run.

OS: Ubuntu 18.04.6

**Comment by nick-youngblut** [comment]
Maybe the output is not correct. Even if I include the target in the set of reference genomes (n=5), I still get `Total number of components in graph: 0` and and empty `*.assigned.scaffolds.fa` file.

**Comment by lcoombe** [comment]
Hi @nick-youngblut,

Hmm that's a strange error, and one that appears to be related to your environment? Those 'no such file or directory' commands appear to be pointing to environment-related files?

Just to double check that it is your environment (vs. the input data), have you run the test demos (in `tests` directory)?

Do you only see those errors when running ntJoin in that environment? Do you see it when running any other tools?

Thank you for your interest in ntJoin!
Lauren

**Comment by nick-youngblut** [comment]
Thanks for the quick response! 

> Do you have rust installed

No, given that it is not part of the [bioconda recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/ntjoin/meta.yaml), but rust could be added: https://anaconda.org/conda-forge/rust

>Just to double check that it is your environment (vs. the input data), have you run the test demos (in tests directory)?

The warning/error occurs even if I provide files paths that don't exist. For example:

```
/ebio/abt3/nyoungblut/.zshenv:.:1: no such file or directory: /ebio/abt3/nyoungblut/.cargo/env
make: *** No rule to make target 'assembly_ref1.fa', needed by 'assembly_ref1.fa.k32.w500.tsv'.  Stop.
```

**Comment by lcoombe** [comment]
Hi @nick-youngblut,

So just checking, is this a fresh/new environment that you made with ntJoin? And do you see those same errors if you try running any other tool installed in your conda environment? 

Also, have you tried running that demo that I suggested? The error that you see `no rule to make target` is expected if the files specified don't exist, so I'm interested in whether with given a set of data files that we know work with ntJoin you still see the same issue with your output files.

Just going through the files involved in that error that you're seeing - The `.zshenv` file will be an environment file for your zsh that is sourced when you open a new shell instance. `.cargo/env` is an environment file related to rust (https://github.com/rust-lang/rustup/issues/2578), so it appears you do have rust installed (Or perhaps did at one time? Or an incomplete installation?), but looks like not in your conda environment. If you look in that `.zshenv` file, does it have a reference to that seemingly non-existent env file?

**Comment by nick-youngblut** [comment]
>So just checking, is this a fresh/new environment that you made with ntJoin? And do you see those same errors if you try running any other tool installed in your conda environment?

This error/warning is specific to ntJoin

>The error that you see no rule to make target is expected if the files specified don't exist

Right, but prior to the `file doesn't exist error`, I still get the `.zshenv` warning. 

>The .zshenv file will be an environment file for your zsh that is sourced when you open a new shell instance

The `~/.zshenv` must have been created sometime recently when I installed rust for another application. I don't see why the `ntJoin` code is interactive with the `.zshenv`, but if I remove the `.zshenv`, then the warning is removed. 

Maybe it has something to do with the use of `make`. You don't see much bioinformatics software using old-school `make` anymore, which might be why this issue will not occur for most people.
