### ISSUE TITLE
Unable to run ntJoin

### ISSUE THREAD

**Issue by sunnyEV** [bcgsc/ntJoin#88]
Hi,
I already denovo assemled the genome using different assemblies, I try to run ntJoiin by providing the closest reference. It pops up an error.  to run ntJoin do we have to provide a bed file for the assembled genome ?

How to assign weights (reference_weights) ? what is the criteria.
**CMD**
**ntJoin assemble target=/home/sun/data/softwares/gam-ngs-1.1b/bin/Lgibbus_scaffolds.spades.CDHIT.fa references=/home/sun/data/softwares/gam-ngs-1.1b/bin/refassmb/GCF_009769545.1_fCycLum1.pri_genomic.fna  prefix=Lgib reference_weights=1** 

> /home/sun/data/softwares/ntJoin/src/indexlr --long --pos -k 32 -w 1000 -t 4 /home/sun/data/softwares/gam-ngs-1.1b/bin/Lgibbus_scaffolds.spades.CDHIT.fa > /home/sun/data/softwares/gam-ngs-1.1b/bin/Lgibbus_scaffolds.spades.CDHIT.fa.k32.w1000.tsv
> samtools faidx /home/sun/data/softwares/gam-ngs-1.1b/bin/Lgibbus_scaffolds.spades.CDHIT.fa
> PYTHONPATH=/home/sun/data/softwares/ntJoin/src/btllib/install/lib/btllib/python   /home/sun/data/softwares/ntJoin/bin/ntjoin_assemble.py -p Lgib -n 1 -s /home/sun/data/softwares/gam-ngs-1.1b/bin/Lgibbus_scaffolds.spades.CDHIT.fa.k32.w1000.tsv -l 1 \
> -r "1" -k 32 -g 20 -G 0 -t 1 --overlap --overlap_gap 20 --btllib_t 4 --overlap_k 15 --overlap_w 10 /home/sun/data/softwares/gam-ngs-1.1b/bin/refassmb/GCF_009769545.1_fCycLum1.pri_genomic.fna.k32.w1000.tsv
> Running ntJoin v1.0.8 ...
> 
> Parameters:
> 	Reference TSV files:  ['/home/sun/data/softwares/gam-ngs-1.1b/bin/refassmb/GCF_009769545.1_fCycLum1.pri_genomic.fna.k32.w1000.tsv']
> 	-s  /home/sun/data/softwares/gam-ngs-1.1b/bin/Lgibbus_scaffolds.spades.CDHIT.fa.k32.w1000.tsv
> 	-l  1.0
> 	-r  1
> 	-p  Lgib
> 	-n  1
> 	-k  32
> 	-g  20
> 	-G  0
> 	-t  1
> Orienting contigs using increasing/decreasing minimizer positions
> 
> 	--overlap
> 	--overlap_gap 20
> 	--overlap_k 15
> 	--overlap_w 10
> 	--btllib_t 4
> 2022-05-28 21:36:15.665511 : Reading minimizers /home/sun/data/softwares/gam-ngs-1.1b/bin/refassmb/GCF_009769545.1_fCycLum1.pri_genomic.fna.k32.w1000.tsv
> 2022-05-28 21:36:18.000433 : Reading minimizers /home/sun/data/softwares/gam-ngs-1.1b/bin/Lgibbus_scaffolds.spades.CDHIT.fa.k32.w1000.tsv
> 
> Weights of assemblies:
> /home/sun/data/softwares/gam-ngs-1.1b/bin/refassmb/GCF_009769545.1_fCycLum1.pri_genomic.fna.k32.w1000.tsv: 1.0
> /home/sun/data/softwares/gam-ngs-1.1b/bin/Lgibbus_scaffolds.spades.CDHIT.fa.k32.w1000.tsv: 1.0
> 
> 2022-05-28 21:36:20.746213 : Filtering minimizers
> 2022-05-28 21:36:22.386346 : Building graph
> 2022-05-28 21:36:22.494978 : Adding vertices
> 2022-05-28 21:36:22.497165 : Adding edges
> 2022-05-28 21:36:22.506183 : Adding attributes
> 2022-05-28 21:36:22.694303 : Printing graph Lgib.mx.dot
> 
> file_name	number	colour
> /home/sun/data/softwares/gam-ngs-1.1b/bin/refassmb/GCF_009769545.1_fCycLum1.pri_genomic.fna.k32.w1000.tsv	0	red
> /home/sun/data/softwares/gam-ngs-1.1b/bin/Lgibbus_scaffolds.spades.CDHIT.fa.k32.w1000.tsv	1	green
> 
> 2022-05-28 21:36:22.953791 : Filtering the graph
> 2022-05-28 21:36:24.308966 : Reading fasta file /home/sun/data/softwares/gam-ngs-1.1b/bin/Lgibbus_scaffolds.spades.CDHIT.fa
> 2022-05-28 21:36:29.125467 : Finding paths
> 
> Total number of components in graph: 2 
> 
> 2022-05-28 21:36:29.557766 : Printing output scaffolds
> Traceback (most recent call last):
>   File "/home/sun/data/softwares/ntJoin/bin/ntjoin_assemble.py", line 1115, in <module>
>     main()
>   File "/home/sun/data/softwares/ntJoin/bin/ntjoin_assemble.py", line 1112, in main
>     Ntjoin().main()
>   File "/home/sun/data/softwares/ntJoin/bin/ntjoin_assemble.py", line 1102, in main
>     self.print_scaffolds(paths, intersecting_regions)
>   File "/home/sun/data/softwares/ntJoin/bin/ntjoin_assemble.py", line 873, in print_scaffolds
>     outfile = self.print_unassigned(assembly, assembly_fa, incorporated_segments, outfile, params)
>   File "/home/sun/data/softwares/ntJoin/bin/ntjoin_assemble.py", line 891, in print_unassigned
>     missing_bed.saveas(self.args.p + "." + assembly + ".unassigned.bed")
>   File "/home/sun/anaconda3/lib/python3.9/site-packages/pybedtools/bedtool.py", line 923, in decorated
>     result = method(self, *args, **kwargs)
>   File "/home/sun/anaconda3/lib/python3.9/site-packages/pybedtools/bedtool.py", line 3362, in saveas
>     fn = self._collapse(
>   File "/home/sun/anaconda3/lib/python3.9/site-packages/pybedtools/bedtool.py", line 1411, in _collapse
>     with out_open_func(fn, "wt") as out_:
> FileNotFoundError: [Errno 2] No such file or directory: 'Lgib./home/sun/data/softwares/gam-ngs-1.1b/bin/Lgibbus_scaffolds.spades.CDHIT.fa.k32.w1000.tsv.unassigned.bed'
> make: *** [/home/sun/data/softwares/ntJoin/ntJoin:221: /home/sun/data/softwares/gam-ngs-1.1b/bin/Lgibbus_scaffolds.spades.CDHIT.fa.k32.w1000.n1.assigned.scaffolds.fa] Error 1
> make: *** Deleting file '/home/sun/data/softwares/gam-ngs-1.1b/bin/Lgibbus_scaffolds.spades.CDHIT.fa.k32.w1000.n1.assigned.scaffolds.fa'

**Comment by lcoombe** [comment]
Hi @sunnyEV,

The issue here is that the input files should be in your current working directory - you can use soft-links to achieve this if necessary. Then, do not specify a full path to the file.
For example, your command would look like:
```
ntJoin assemble target=Lgibbus_scaffolds.spades.CDHIT.fa references=GCF_009769545.1_fCycLum1.pri_genomic.fna prefix=Lgib reference_weights=2
```

As for the reference weights, there's some guidance here: https://github.com/bcgsc/ntJoin#parameter-considerations
Generally, if you are using a target and a reference, I would suggest using `target_weight=1 reference_weights=2`

Hope that helps - thank you for your interest in ntJoin!
Lauren
