### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by chunlinxiao** [bcgsc/ntJoin#95]
I'm trying to install the required dependencies using

pip3 install -r requirements.txt

but encountered an error with btllib, and error listed below:

ERROR: Could not find a version that satisfies the requirement btllib (from versions: none)
ERROR: No matching distribution found for btllib

Our system  is CentOS.

Can you provide some suggestions?

thanks

**Comment by lcoombe** [comment]
Hi @chunlinxiao,

Have you tried installing ntJoin (and dependencies) using conda? btllib is not available from PyPI, but is available from conda. Alternatively, you can install this dependency from source, but we recommend using the conda environment.

Thanks for your interest in ntJoin!
Lauren

**Comment by chunlinxiao** [comment]
thanks for quick reply.  I did try conda earlier, but failed for both htllib and ntjoin.

What I did was below:

>conda config --add channels bioconda 
>conda config --add channels conda-forge
>conda install -c bioconda -c conda-forge ntjoin

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: - 

Looks like it was not able to "Solving environment" as it repeated the same processes after failing.

Thanks for the help.

**Comment by chunlinxiao** [comment]
Here is the full log of the new attempt:


>conda config --add channels bioconda
Warning: 'bioconda' already in 'channels' list, moving to the top

>conda config --add channels conda-forge
Warning: 'conda-forge' already in 'channels' list, moving to the top

>conda install ntjoin

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                        

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - ntjoin -> python[version='>=3.10,<3.11.0a0|>=3.6,<3.7.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']

Your python: python=2

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions



However, when I checked our python version, it is 3.9.16.

>python --version
Python 3.9.16

**Comment by lcoombe** [comment]
Thanks @chunlinxiao - And is this a fresh (newly created) conda environment, or one that you've previously installed multiple tools in?

**Comment by chunlinxiao** [comment]
finally got it installed with brand-new conda env:

myconda/bin/ntJoin

ntJoin: Scaffolding assemblies using reference assemblies and minimizer graphs
ntJoin v1.1.1
Usage: ntJoin assemble target=<target scaffolds> references='List of reference assemblies' reference_weights='List of weights per reference assembly'

Options:
target                  Target assembly to be scaffolded in fasta format
references              List of reference files (separated by a space, in fasta format)
target_weight           Weight of target assembly [1]
reference_weights       List of weights of reference assemblies

Thank @lcoombe so much for your help - I'm going to give ntjoin a try soon !!

**Comment by lcoombe** [comment]
Excellent - I'm very glad to hear that you got a successful installation! Good luck with your ntJoin runs!
